### ISSUE TITLE
Switch to Mozilla redash and update links

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/redash-ui-tests#108]
Since we are targeting STMO we should use that within out ```docker-compose.yml``` and also update any links referencing ```getredash/redash```

**Comment by jrbenny35** [comment]
For the docs and such should we no longer promote/direct upstream redash?

**Comment by jezdez** [comment]
@jrbenny35 For the time being that's the compromise that we agreed to in Berlin, yeah.
