### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by hackebrot** [mozilla/redash-ui-tests#2]
When submitting a pull request against this repo, we would like to get automated feedback on whether the suite is still working on all of the existing tests and new tests pass.

- [x] Decide on a CI product
- [x] Set up CI for this project

**Comment by jrbenny35** [comment]
I think circleci should be out CI system as it has great docker support.

**Comment by hackebrot** [comment]
Sounds good! 👍

**Comment by hackebrot** [comment]
Resolved in #34
