### ISSUE TITLE
Add python dependency updater

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/redash-ui-tests#20]
We should add pyup to keep the dependencies updated.

**Comment by aayush420** [comment]
I'm trying to add pyup.
But it's saying no requirements file found. 
How to overcome the issue??

![image](https://user-images.githubusercontent.com/16898783/41602202-e4760ac2-73f7-11e8-8b08-fe8c0223a76a.png)

**Comment by jrbenny35** [comment]
@aayush420 add this to your ```.pyup.yml```:
```
requirements:
  - Pipfile
  - Pipfile.lock
```

**Comment by jrbenny35** [comment]
Fixed in #27
