### ISSUE TITLE
Add Test: Creating an Admin 

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/redash-ui-tests#22]
### Prerequisites
- The redash instance has not been setup

### UI Test

Action | Result
------------ | -------------
Open redash instance URI | Page displays Redash setup page, URL has ```/setup``` within it. 
Input user information | User logs in and the Redash homepage is shown with the user logged in.

This will also solve setting up the redash instance we use for testing.

**Comment by hackebrot** [comment]
Users don't have to set up a Redash instance and even though I'm not familiar with the upgrade story for admins, I don't think it's strictly necessary for us to automate this. I'd say it's safe to run the tests against a configured Redash instance. That being said we a way to automatically do this when starting up the server.

**Comment by jrbenny35** [comment]
I found [this](https://github.com/getredash/redash/blob/722678f6d101491caba0e1a6858ccce873fb72ec/tests/factories.py#L189), maybe we can use that, or somehow issue a call to it.

**Comment by hackebrot** [comment]
Closing this issue for now as most of our users don't set up new Redash instances and it's not a priority to get UI testing in place for the admin interface.
