### ISSUE TITLE
Write "Run the test suite" guide

### ISSUE THREAD

**Issue by hackebrot** [mozilla/redash-ui-tests#46]
Write "Run the test suite" section for our [getting-started][getting-started] guide 📝 

[getting-started]: https://redash-ui-tests.readthedocs.io/en/latest/tutorials/getting-started/

**Comment by jrbenny35** [comment]
How does this look?

To run the test suite make sure you have docker installed and can execute docker run commands. Then simply

```make build``` followed by ```make docker-ui-tests```,
or as 1 command ```make build; make docker-ui-tests```.

This will build the docker image and then execute the tests within the docker image.

**Comment by hackebrot** [comment]
Image being a newcomer to **redash-ui-tests** and you successfully [installed the software requirements][getting-started] and [cloned the project][getting-started], now what do you need to know to be able to run the tests on your local machine?

It's important to not only provide a reference for commands to run, but also explain concepts even if they seem obvious. I suggest to explain the necessary docker and docker-compose commands and don't expect users to have ``make`` installed on their system. It's important to explain concepts even if they seem obvious. Try to avoid words such as "easily", "obviously", "simply", or "just".

[getting-started]: https://redash-ui-tests.readthedocs.io/en/latest/tutorials/getting-started/
