### ISSUE TITLE
Increase max-line-length to 88

### ISSUE THREAD

**Issue by hackebrot** [mozilla/redash-ui-tests#53]
Our source code will be more verbose with type hints (#51) and less readable with a max line length of 79 characters. I suggest to increase this to 88 characters, which is the default in black.

**Comment by jrbenny35** [comment]
I gave this a shot
```
def fixture_create_user(
    root_session: Session, server_url: str, user_factory: UserFactory
) -> typing.Callable:
```

I don't like it 🤭
