### ISSUE TITLE
Add test: Searching queries by complete name

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash-ui-tests#60]
### Prerequisites

- User is logged in
- The query with the name mentioned in the test is created

### UI Test

Action | Result
------------ | -------------
Navigate to landing page | Page displays "Search queries..." input and button
Input the complete query name and click button | Browser opens queries page, "Search" tab is selected, page contains table, table contains only relevant items, the query with the complete name used in test is displayed as the first result.

**Comment by jrbenny35** [comment]
We currently have this test already.
