### ISSUE TITLE
Add test: Searching for queries with special characters in the name

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash-ui-tests#63]
### Prerequisites

- User is logged in
- Query with special characters in the name

### UI Test

Action | Result
------------ | -------------
Navigate to landing page | Page displays "Search queries..." input and button
Input the name of a query that contains special characters and click button | Browser opens queries page, "Search" tab is selected, page contains table, table contains only relevant items, the query that contains special characters in the name is displayed

**Comment by jrbenny35** [comment]
What would classify as a special character? Like ```@```, ```/```, or √∫˜µƒç©˙¨ß ?

**Comment by madalincm** [comment]
In my manual tests I usually use characters like @ ? / # $ & ( ) { } as there are some queries that contain those characters. So only character that you directly find on your keyboard.
