### ISSUE TITLE
Create issues for test cases

### ISSUE THREAD

**Issue by hackebrot** [mozilla/redash-ui-tests#7]
Create a series of GitHub issues for test cases to automate.

**Comment by hackebrot** [comment]
@madalincm will add a number of issues for test cases! yay!

**Comment by madalincm** [comment]
@hackebrot  Do we use the "tests" label to mark this kind of issues?

**Comment by hackebrot** [comment]
@madalincm yes, exactly!

**Comment by hackebrot** [comment]
Done [tests issues](https://github.com/mozilla/redash-ui-tests/issues?q=is%3Aopen+is%3Aissue+label%3Atests). Thanks @madalincm! 🚀
