### ISSUE TITLE
Publish button publishes an unpublished query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash-ui-tests#89]
### Prerequisites

- User is logged in
- At least one unpublished query

### UI Test

Action | Result
------------ | -------------
Navigate to a query  /id page for an unpublished query | the “Publish” button is displayed, the “Unpublished” tag is displayed
Click on the “Publish” button | The query is published, the “Publish” button is no longer displayed, the “Unpublished” tag is no longer displayed

**Comment by jrbenny35** [comment]
Fixed in #103
