### ISSUE TITLE
Options button - Fork creates a copy of the query and redirects the user to the new query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash-ui-tests#91]
### Prerequisites

- User is logged in
- At least one query

### UI Test

Action | Result
------------ | -------------
Navigate to a query  /id page  | Options button is displayed
Click on the Options button | A drop down menu is displayed, Fork link displayed in dropdown
Click on the Fork link | User is redirected to the new query page, New query page contains the “Copy of (#xx)”  (where xx is id of the previous query) text and the title of the previous query

**Comment by jrbenny35** [comment]
Fixed in #103
