### ISSUE TITLE
Options button - Archive archives the query

### ISSUE THREAD

**Issue by madalincm** [mozilla/redash-ui-tests#92]
### UI Test

Action | Result
------------ | -------------
Navigate to a query  /id page  | Options button is displayed
Click on the Options button | A drop down menu is displayed, Archive link displayed in dropdown
Click on the Archive link | A pop-up is displayed with 2 buttons “Cancel” and “Archive”
Click on the Archive button | The query is archived, the “Archived” tag is displayed

**Comment by jrbenny35** [comment]
Fixed in #103
